[package]
name = "mnger-app"
version = "0.1.0"
authors = ["Maykol Laguna <lagunamichael2@outlook.com>"]
edition = "2021"
rust-version = "1.79"

[workspace]
members = [".", "nebula", "altera", "preon"]

[dependencies]
mnger-nebula = { path = "nebula" }