name: Rust

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: "1.79.0"
          profile: minimal
          override: true

      - name: Install Clang and LLD
        run: sudo apt-get install -y clang lld

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose
